knp_paginator:
    page_range: 4          # Numărul de pagini vizibile în navigare
    default_options:
        page_name: page    # Numele variabilei din query string
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'

